### PR TITLE
Scripts for making nuget packages for both Platform and Platform's modules

### PR DESCRIPTION
**Pull request by arsen74**
Also added nuspce files for Platform and several modules as an example (v3 beta)

### CODE REVIEW

**Review by tatarincev — COMMENTED** [review]
Why do we need use this nuget spec for each project? It will be very tricky to update it before each release manually. Why we can't use for this `  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>`  MS project option?

**Comment by Woland2k** [comment]
we can also simply automate this on CI, no need to change anything

**Review by tatarincev — COMMENTED** [review]
And please remove binary file  `nuget.exe` from github source control

**Comment by arsen74** [comment]
1. We have 2 options here: use nuspec file if existing (as priority) and ordinal csproj build if not (standard way). So 2 options let make it flexible.
2. Nuget pack internaly uses msbuild and if project has such <GeneratePackageOnBuild>true</GeneratePackageOnBuild> option it will use it
3. CI can use such scripts as another building step as well as manual execution

**Comment by arsen74** [comment]
Fixed issues after review

**Review by tatarincev — APPROVED** [review]

**Pull request merged**
