### PR TITLE
Allow disabling https login

### PR DESCRIPTION
**Pull request by JustinBerger**
For things like nginx https proxy which hide the https work from kestrel, useful for linux/docker deployments.

### CODE REVIEW

**Review by tatarincev — COMMENTED** [review]
I've made some like this changes before, but it didn't work anyway  you can't simply disable https by this way. Unfortunately I can't remember what concrete error I've faced. but I can check again

**Comment by JustinBerger** [comment]
You need this to allow the login to not use Https, and you need to disable Https in kestrel. However, there may be another setting that needs to be changed. For now I'll just set our environment to run as Development, until I can figure out all the settings that need to be changed to fully bypass https.

**Comment by JustinBerger** [comment]
In order to use virto without https you need the code change in this pull request and the following added to the appsettings.json file:
"Kestrel": {
        "Endpoints": {
           "Http": {
                "Url": "http://localhost:801"
            }
        }
    }
This is enough to allow logging in, and navigating throughout the app.
Without the code change, OpenIdDict rejects all login attempts, even with https disabled.

**Comment by kevinchalet** [comment]
@JustinBerger disabling the HTTPS requirement will certainly hide the error message, but all the middleware in your ASP.NET Core application that rely on the "request scheme" (typically everything that uses 302 redirects) will not work properly.

What you is really need is the "forwarded headers" middleware. Here's the doc for nginx: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2

**Comment by tatarincev** [comment]
@JustinBerger  Thanks for your participation in the discussion, I really appreciate of you `OpenIddict`  server which you did 👍 
Guys I'm just wondering if no any trivial solution to disable https for production mode I can close this issue then?

**Comment by kevinchalet** [comment]
Haha, thanks for the kind words 😄 

Adding an option to disable the transport security requirement is probably not a bad thing, but it shouldn't be used as a way to avoid using the "forwarded headers" middleware, which will still be required to determine whether TLS was used or not earlier in the request processing (typically, by a proxy server doing TLS termination).

**Comment by JustinBerger** [comment]
I'll close out this PR, and start working on using forwarded headers middleware instead. I like that approach better.

**Pull request closed without merging**
